### ISSUE TITLE
iOS MissingPluginException(No implementation found for method listen on channel medcorder_audio_events)

### ISSUE THREAD

**Issue by Shakle** [evrone/flutter_audio#24]
Android works ok, but iOS shows this on init

The following MissingPluginException was thrown while activating platform stream on channel medcorder_audio_events:
MissingPluginException(No implementation found for method listen on channel medcorder_audio_events)

When the exception was thrown, this was the stack: 
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:517:29)
#3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:503:64)
#8      new MedcorderAudio (package:medcorder_audio/medcorder_audio.dart:13:43)
...

**Comment by rayliverified** [comment]
I'm getting this error as well.

Flutter Stable v1.17.3

> The following MissingPluginException was thrown while activating platform stream on channel
> medcorder_audio_events:
> MissingPluginException(No implementation found for method listen on channel medcorder_audio_events)
> When the exception was thrown, this was the stack:
> #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
> <asynchronous suspension>
> #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
> #2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:519:29)
> #3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:505:64)
> #8      new MedcorderAudio (package:medcorder_audio/medcorder_audio.dart:13:43)
> #9      new _MyAppState (package:medcorder_audio_example/main.dart:15:36)
> #10     MyApp.createState (package:medcorder_audio_example/main.dart:11:36)
> #11     new StatefulElement (package:flutter/src/widgets/framework.dart:4591:25)
> #12     StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:894:38)
> #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3441:40)
> #14     Element.updateChild (package:flutter/src/widgets/framework.dart:3214:18)
> #15     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1148:16)
> #16     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1119:5)
> #17     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1061:17)
> #18     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2607:19)
> #19     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1060:13)
> #20     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:941:7)
> #21     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:922:7)
> (elided 15 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)

**Comment by huxaiphaer** [comment]
Did anyone of you get the solution @searchy2 and @Shakle ?, am also stuck here

**Comment by tomfriedhof** [comment]
It doesn't look like this was built to work for iOS. If you do a search for any of the channel methods in the repo, you won't find any. There are only java implementations.

**Bummer that this wasn't developed for both platforms.**
